eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8769
spring:
  application:
    name: gateway-zuul
zuul:
  routes:
    api-a:
      path: /api-sr/**
      serviceId: service-ribbon
    api-b:
      path: /api-sf/**
      serviceId: service-feign
